[package]
name = "decision_maker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.*"
rand = "0.8.5"
serde = "1.0.*"
toml = "0.8.*"
itertools = "0.13.*"
rand_distr = "0.4.3"
clap = "4.5.*"
